# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='photo_category',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='photo_location',
        ),
    ]
